### ISSUE TITLE
Q: Rest client alternative?

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [postcode-nl/PostcodeNl_Api_Client#1]
I assume this is the alternative package we should use now instead of https://github.com/postcode-nl/PostcodeNl_Api_RestClient which has been archived. If so then I also assume this package is considered stable, so can you guys mark this with release "1.0.0" or add the necessary bugfixes and then tag it.

Please let me know I assumed all this correctly :smile:

**Comment by JozefVerhoef** [comment]
Hi Geoffrey, your assumptions are correct :)

1.0.0 has now been tagged.

**Comment by GeoffreyDijkstra** [comment]
@JozefVerhoef maybe you can also update the old repository to report this one as alternative in composer.json but also point github users in the right direction :smile:
