### ISSUE TITLE
Assets in autocomplete.html example not availabe

### ISSUE THREAD

**Issue by artifex-media** [postcode-nl/PostcodeNl_Api_Client#10]
Hi,

The assets in the autocomplete.html example file are not available anymore, they throw an 418 error.
Could this be fixed in order to get a working and clear demo?

```
418:
<link rel="stylesheet" href="https://api.postcode.nl/static/3.2.16.0/css/autocomplete-address.css">
<script src="https://api.postcode.nl/static/3.2.16.0/js/PostcodeNl/AutocompleteAddress.min.js"></script>
```

**Comment by BastiaanGrutters** [comment]
Thanks for reporting this, it is resolved in the new release [1.0.4](https://github.com/postcode-nl/PostcodeNl_Api_Client/releases/tag/1.0.4)
