### ISSUE TITLE
Add this package as a suggestion for the previous package

### ISSUE THREAD

**Issue by acjbizar** [postcode-nl/PostcodeNl_Api_Client#6]
[The README of the previous project](https://github.com/postcode-nl/PostcodeNl_Api_RestClient/blob/master/README.md) mentions this project as a replacement. So far so good.

However, when I run a `composer install` on a project that has `postcode-nl/api-restclient` as a requirement, I get the following feedback:

> Package postcode-nl/api-restclient is abandoned, you should avoid using it. No replacement was suggested.

It would make sense to suggest `postcode-nl/api-client` as a replacement instead.

**Comment by BastiaanGrutters** [comment]
I am not sure where that message is coming from but `postcode-nl/api-client` is set as the recommended replacement, see:
https://github.com/postcode-nl/PostcodeNl_Api_RestClient/commit/31c059fd920b6c50f5b18dcac1898bf70c43605f#diff-d2ab9925cad7eac58e0ff4cc0d251a937ecf49e4b6bf57f8b95aab76648a9d34
