### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by witi77** [postcode-nl/PostcodeNl_Api_Client#7]
Hi there,

Is there anymore documentation / real code examples available for this library? It's hard to evaluate for me if i am going to write something myself of invest time in this to get this working into my project.

Thanks in advance for your reply.

**Comment by JozefVerhoef** [comment]
Hi! 

The API methods implemented by the client are all documented here: https://api.postcode.nl/documentation
There is also a live demo of the international methods here: https://api.postcode.nl/documentation/international/overview

In addition, the library contains a simple example page that demonstrates the functionality (see the example directory). You need to register a test account to get the necessary API credentials for this example.

If you have any specific questions, you can reach us here: https://www.postcode.nl/en/services/contact
