### ISSUE TITLE
Destructor should check if property is set before attempting to use it.

### ISSUE THREAD

**Issue by cmanley** [postcode-nl/PostcodeNl_Api_Client#8]
https://github.com/postcode-nl/PostcodeNl_Api_Client/blob/4001d518f5cfd9dcff6b0affe5f57592b00965a8/src/PostcodeNl/Api/Client.php#L264

Like this:
`$this->_curlHandler && curl_close($this->_curlHandler);`

The reason is because constructor (or that of child class) can throw an exception. The destructor will still be called then.

**Comment by cmanley** [comment]
P.S. _curlHandler is really a handle not a handler.

**Comment by BastiaanGrutters** [comment]
Thanks for your feedback, it has been updated.
